name: studypilot
description: StudyPilot - Self Study & Exam Management App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter